PROFILE_NAMES = DEVICE_globalscale_espressobin DEVICE_globalscale_espressobin-emmc DEVICE_globalscale_espressobin-v7 DEVICE_globalscale_espressobin-v7-emmc DEVICE_marvell_armada-3720-db DEVICE_gl-mv1000 DEVICE_gl-mv1000-emmc
DEVICE_globalscale_espressobin_NAME:=ESPRESSObin (Marvell Armada 3700 Community Board)
DEVICE_globalscale_espressobin_HAS_IMAGE_METADATA:=1
DEVICE_globalscale_espressobin_SUPPORTED_DEVICES:=globalscale,espressobin
DEVICE_globalscale_espressobin_PACKAGES:=
DEVICE_globalscale_espressobin-emmc_NAME:=ESPRESSObin eMMC (Marvell Armada 3700 Community Board)
DEVICE_globalscale_espressobin-emmc_HAS_IMAGE_METADATA:=1
DEVICE_globalscale_espressobin-emmc_SUPPORTED_DEVICES:=globalscale,espressobin-emmc
DEVICE_globalscale_espressobin-emmc_PACKAGES:=
DEVICE_globalscale_espressobin-v7_NAME:=ESPRESSObin V7 (Marvell Armada 3700 Community Board)
DEVICE_globalscale_espressobin-v7_HAS_IMAGE_METADATA:=1
DEVICE_globalscale_espressobin-v7_SUPPORTED_DEVICES:=globalscale,espressobin-v7
DEVICE_globalscale_espressobin-v7_PACKAGES:=
DEVICE_globalscale_espressobin-v7-emmc_NAME:=ESPRESSObin V7 eMMC (Marvell Armada 3700 Community Board)
DEVICE_globalscale_espressobin-v7-emmc_HAS_IMAGE_METADATA:=1
DEVICE_globalscale_espressobin-v7-emmc_SUPPORTED_DEVICES:=globalscale,espressobin-v7-emmc
DEVICE_globalscale_espressobin-v7-emmc_PACKAGES:=
DEVICE_marvell_armada-3720-db_NAME:=Marvell Armada 3720 Development Board DB-88F3720-DDR3
DEVICE_marvell_armada-3720-db_HAS_IMAGE_METADATA:=1
DEVICE_marvell_armada-3720-db_SUPPORTED_DEVICES:=marvell,armada-3720-db
DEVICE_marvell_armada-3720-db_PACKAGES:=
DEVICE_gl-mv1000_NAME:=GL.iNet GL-MV1000
DEVICE_gl-mv1000_HAS_IMAGE_METADATA:=1
DEVICE_gl-mv1000_SUPPORTED_DEVICES:=gl-mv1000
DEVICE_gl-mv1000_PACKAGES:=e2fsprogs ethtool mkf2fs kmod-fs-vfat kmod-usb2 kmod-usb3 kmod-usb-storage
DEVICE_gl-mv1000-emmc_NAME:=GL.iNet GL-MV1000 EMMC
DEVICE_gl-mv1000-emmc_HAS_IMAGE_METADATA:=0
DEVICE_gl-mv1000-emmc_SUPPORTED_DEVICES:=gl-mv1000-emmc
DEVICE_gl-mv1000-emmc_PACKAGES:=
